name: Auto Load Test Every 5 Minutes

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  loadtest:
    runs-on: ubuntu-latest

    steps:
      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg ca-certificates
          curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Create Load Test Script
        run: |
          cat << 'EOF' > test.js
          import http from "k6/http";
          import { check, sleep } from "k6";

          export const options = {
            scenarios: {
              constant_rate_test: {
                executor: "constant-arrival-rate",
                rate: 450,
                timeUnit: "1s",
                duration: "20s",
                preAllocatedVUs: 600,
                maxVUs: 800,
              },
            },
          };

          const agents = [
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/122.0 Safari/537.36",
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 Version/17.0 Safari/605.1.15",
            "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/120.0 Safari/537.36",
            "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 Version/16.0 Mobile Safari/604.1"
          ];

          function randomAgent() {
            return agents[Math.floor(Math.random() * agents.length)];
          }

          export default function () {

            const userAgent = __ENV.USER_AGENT || randomAgent();

            const params = {
              headers: {
                "User-Agent": userAgent,
                "Referer": "https://xnxx.com/",
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                "Accept-Language": "en-US,en;q=0.9",
                "Connection": "keep-alive",
                "Cache-Control": "no-cache"
              }
            };

            const res = http.get("https://azrogo.net/gdpr", params);

            check(res, {
              "status is 200": (r) => r.status === 200,
            });

            sleep(1);
          }
          EOF

      - name: Run Load Test
        env:
          USER_AGENT: ${{ secrets.USER_AGENT }}
        run: k6 run test.js
